name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build g++ pkg-config libeigen3-dev

      - name: Configure
        run: meson setup build --buildtype=release

      - name: Build
        run: meson compile -C build

      - name: Install to release directory
        run: meson install -C build --destdir release

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: neural_network_artifacts
          path: |
            build/release/usr/local/bin/neural_network
            build/release/usr/local/lib64/libneural_network.so

      - name: Create or update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          body: "Automated release of latest commit to master"
          draft: false
          prerelease: false
          files: |
            build/release/usr/local/bin/neural_network
            build/release/usr/local/lib/libneural_network.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
